# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_analysisresult_extended_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="body_text",
            field=models.TextField(blank=True),
        ),
    ]
