# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_analysisresult_body_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="authentication_verification",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
