# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_analysisresult_authentication_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
