# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_analysisresult_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
